# Generated by Django 2.0.3 on 2019-09-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default='pwd'),
            preserve_default=False,
        ),
    ]
