# Generated by Django 2.0.3 on 2019-09-24 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenUser',
            fields=[
                ('user_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('password', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
