# Generated by Django 2.0.5 on 2019-09-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190924_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
