# Generated by Django 2.0.7 on 2019-09-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190918_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='address',
            new_name='shop_address',
        ),
        migrations.RemoveField(
            model_name='chatline',
            name='line_id',
        ),
        migrations.RemoveField(
            model_name='chatline',
            name='writer_id',
        ),
        migrations.AddField(
            model_name='chatline',
            name='dest_id',
            field=models.CharField(default='', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatline',
            name='msg_id',
            field=models.CharField(default='', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatline',
            name='src_id',
            field=models.CharField(default='', max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='admin',
            name='phone_no',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatline',
            name='order_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='chatline',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='med_id',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='order_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='orders',
            name='admin_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivered_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='est_delivery_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('rejected', 'REJECTED'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=36),
        ),
    ]
