# Generated by Django 2.2.5 on 2019-09-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='pic',
            field=models.ImageField(blank=True, upload_to='pic'),
        ),
    ]
