# Generated by Django 2.2.5 on 2019-09-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190919_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='pic',
            field=models.FileField(upload_to=''),
        ),
    ]
