# Generated by Django 2.0.3 on 2019-09-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190919_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
